package views;

import java.time.LocalDate;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import clases.Prestamo;
import utils.Almacenamiento;
import utils.AppUtils;
import utils.Constantes;

/**
 *
 * @author victortinoco
 */
public class ListaPrestamosView extends javax.swing.JFrame {

    private final String[] columnas = new String[] { "Id", "Libro", "Fecha de préstamo", "fecha de devolución", "Estado", "Observaciones" };

    private DefaultTableModel defaultTableModel = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 3;
        }
    };

    /**
     * Creates new form PrestamosView
     */
    public ListaPrestamosView() {
        initComponents();
        tblLista.setModel(defaultTableModel);

        // llenamos la tabla la primera ves que carga la pantalla
        for (Prestamo item : Almacenamiento.instance().getPrestamos()) {
            defaultTableModel.addRow(convertirPrestamoATableRow(item));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        txtFechaPrestamo1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFechaPrestamo2 = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblListaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblLista);

        try {
            txtFechaPrestamo1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFechaPrestamo1.setSize(new java.awt.Dimension(130, 23));

        jLabel1.setText("Fecha de préstamo");

        try {
            txtFechaPrestamo2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnDevolver.setText("Devolver");
        btnDevolver.setEnabled(false);
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFechaPrestamo1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaPrestamo2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDevolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRegresar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaPrestamo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnDevolver)
                    .addComponent(btnRegresar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String[] convertirPrestamoATableRow(Prestamo item) {
        String nombreLibro = item.getLibro() != null ? item.getLibro().getNombre() : "";

        return new String[] {item.getId() + "", nombreLibro, item.getFechaPrestamoStr(), item.getFechaDevolucionStr(), item.getEstado(), item.getObservacionDevolucion()};
    }

    private void filtrarTabla() {
        LocalDate fechaPrestamoDesde = null;
        LocalDate fechaPrestamoHasta = LocalDate.now();
        
        List<String[]> datosFiltrados = Almacenamiento.instance().getPrestamos().stream().filter((item) -> {
            var esFechaMayor = fechaPrestamoDesde == null ? true : AppUtils.isLocalDateBeforeOrEqual(item.getFechaPrestamo().toLocalDate(), fechaPrestamoDesde);
            var esFechaMenor = fechaPrestamoHasta == null ? true : AppUtils.isLocalDateBeforeOrEqual(item.getFechaPrestamo().toLocalDate(), fechaPrestamoHasta);

            if (!esFechaMayor && !esFechaMenor) {
                return false;
            }

            return true;
        }).map((item) -> convertirPrestamoATableRow(item)).toList();

        defaultTableModel.setRowCount(0);

        for (String[] item : datosFiltrados) {
            defaultTableModel.addRow(item);
        }
    }

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        var registroView = new RegistroPrestamoView();
        registroView.setLocationRelativeTo(null);
        registroView.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtFechaPrestamo1.setText("");
        txtFechaPrestamo2.setText("");
        btnDevolver.setEnabled(false);
        tblLista.clearSelection();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        filtrarTabla();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        String respuesta = JOptionPane.showInputDialog(null, "Ingrese observaciones si es necesario",
                "¿Desea registar la devolución del libro?", JOptionPane.QUESTION_MESSAGE);

       if (respuesta == null) {
           return;
       }

        int rowSelected = tblLista.getSelectedRow();
        String idString = (String) defaultTableModel.getValueAt(rowSelected, 0);

        try {
            Almacenamiento.instance().registrarDevolucionPrestamo(Long.parseLong(idString), respuesta);
            JOptionPane.showMessageDialog(null, "Datos actualizados");
            filtrarTabla();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        var principalView = new PrincipalView();
        principalView.setLocationRelativeTo(null);
        principalView.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tblListaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaMouseReleased
        int rowSelected = tblLista.getSelectedRow();
        String idString = (String) defaultTableModel.getValueAt(rowSelected, 0);

        try {
            var itemPrestamo = Almacenamiento.instance().getPrestamoPorId(Long.parseLong(idString));

            // si aún no se encuentra en estado prestado, activamos el boton de devolver
            if (itemPrestamo != null && itemPrestamo.getEstado().equals(Constantes.ESTADO_PRESTAMO_PRESTADO)) {
                btnDevolver.setEnabled(true);
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_tblListaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPrestamosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPrestamosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPrestamosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPrestamosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPrestamosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLista;
    private javax.swing.JFormattedTextField txtFechaPrestamo1;
    private javax.swing.JFormattedTextField txtFechaPrestamo2;
    // End of variables declaration//GEN-END:variables
}
